version: 2.1
jobs: 
  Lets-Try-This-Again: 
    docker:       
      - image: "circleci/python:3.6.4"      
    steps:       
     - checkout  
     - run:
          command: |  
            sudo pip install pipenv
            pipenv install
            python speed-typing.py





workflows:
 version: 2
 Example_Workflow:
   jobs:

     - Lets-Try-This-Again
     
